### ISSUE TITLE
Agency markdown files not being generated

### ISSUE THREAD

**Issue by twobyte** [pwyf/aid-transparency-index#39]
Hi Andy,

I was hoping you might be able to shine some light on this python generation script?

Running `python gen/data-gen.py` is successfully converting the _data/source-results.csv into _data/results.json, but the pages/agencies/* markdown files are not being regenerated as I would expect.

It appears as though if I just uncomment the content below this line this should work, but what is the Google spreadsheet referenced in there?

https://github.com/pwyf/aid-transparency-index/blob/a1b5db4d1f1ed950f32547ba2ed38741015be3d0/gen/data-gen.py#L161

With no commenting available, I really appreciate any help trying to understand what is going on here. Thanks!

**Comment by andylolz** [comment]
> With no commenting available

So [the README](https://github.com/pwyf/aid-transparency-index/blob/master/README.md) says:

> ### Content that can be modified:
> 
>  * [2018 ATI site content](https://github.com/pwyf/aid-transparency-index/blob/master/pages)

The idea was that this content would be manually added / modified.

However, you are right that I did create an initial import step from a google spreadsheet, just because that’s where others created the content, so it was just more convenient to automate the initial import.

> what is the Google spreadsheet referenced in there?

I don’t remember, but you can paste the URL directly into the browser, or hack it a bit for the HTML version: 
https://docs.google.com/spreadsheets/d/1LJR7yznASN0VJ4qhnkWFSltDFobN8X4N0mQBiNDOThg/edit

Hope that helps

**Comment by twobyte** [comment]
That clarification is really helpful, thanks @andylolz.
